<Project>

  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <Deterministic>true</Deterministic>
    <Product>Storava</Product>
    <Company>Storava</Company>
    <Version>0.1.0</Version>
    <NeutralLanguage>en</NeutralLanguage>
  </PropertyGroup>

</Project>
