using System.Globalization;
using System.Text.Json;
using Storava.Domain.Entities;
using Storava.Domain.Enums;
using Storava.Reporting.Export;
using Storava.Reporting.Model;

namespace Storava.Reporting.Tests;

public class ReportWriterTests
{
    private static StorageReport SampleReport(bool withAi = false) => new()
    {
        SessionId = "session-1",
        RootPath = @"C:\Users\Ali\source",
        Language = "en",
        GeneratedAt = new DateTimeOffset(2026, 7, 26, 10, 0, 0, TimeSpan.Zero),
        ScanStartedAt = new DateTimeOffset(2026, 7, 26, 9, 55, 0, TimeSpan.Zero),
        ScanDuration = TimeSpan.FromMinutes(5),
        TotalSize = 12L * 1024 * 1024 * 1024,
        FileCount = 11798,
        FolderCount = 3138,
        ErrorCount = 4,
        Categories =
        [
            new ReportCategory(StorageCategory.BuildArtifacts, "Build artifacts", 8L * 1024 * 1024 * 1024, 0.66),
            new ReportCategory(StorageCategory.PackageCaches, "Package caches", 4L * 1024 * 1024 * 1024, 0.34)
        ],
        LargestItems =
        [
            new ReportItem(@"C:\Users\Ali\source\app\bin", "bin", 3L * 1024 * 1024 * 1024,
                StorageCategory.BuildArtifacts, "Build artifacts", false)
        ],
        Recommendations =
        [
            new ReportRecommendation(
                "Build output (bin / obj)",
                @"C:\Users\Ali\source\app\bin",
                "Compiled binaries, regenerated by the next build.",
                3L * 1024 * 1024 * 1024,
                RiskLevel.Low,
                "Low risk",
                StorageCategory.BuildArtifacts,
                "Build artifacts",
                ".NET",
                "Run 'dotnet clean'.",
                "Close the IDE first.",
                0.72,
                CanDelete: true,
                CanMove: false,
                CanRegenerate: true,
                RecommendationSource.RuleEngine)
        ],
        Ai = withAi
            ? new ReportAiSection(
                "openrouter/free",
                new DateTimeOffset(2026, 7, 26, 10, 5, 0, TimeSpan.Zero),
                "Mostly developer build output.",
                "Build artifacts",
                "The drive is dominated by rebuildable output.",
                ["Build output accounts for two thirds of the scan."],
                ["Clean old build folders."],
                AcceptedCount: 1,
                RejectedCount: 2)
            : null
    };

    // --- JSON ---

    [Fact]
    public void Json_RoundTripsTheReport()
    {
        string json = new JsonReportWriter().Write(SampleReport(withAi: true));

        using var document = JsonDocument.Parse(json);
        var root = document.RootElement;

        Assert.Equal("session-1", root.GetProperty("SessionId").GetString());
        Assert.Equal(11798, root.GetProperty("FileCount").GetInt32());
        Assert.Equal("openrouter/free", root.GetProperty("Ai").GetProperty("ModelName").GetString());
    }

    [Fact]
    public void Json_WritesEnumsAsReadableNames()
    {
        string json = new JsonReportWriter().Write(SampleReport());

        Assert.Contains("BuildArtifacts", json);
        Assert.DoesNotContain("\"Category\": 7", json);
    }

    [Fact]
    public void Json_KeepsPersianTextUnescaped()
    {
        string json = new JsonReportWriter().Write(new StorageReport
        {
            SessionId = "s",
            RootPath = @"D:\داده‌ها",
            Language = "fa",
            Categories = [new ReportCategory(StorageCategory.Media, "رسانه", 1024, 1)]
        });

        Assert.Contains("رسانه", json);
        Assert.DoesNotContain("\\u0631", json);
    }

    // --- CSV ---

    [Fact]
    public void Csv_HasAHeaderAndOneRowPerRecommendation()
    {
        string csv = new CsvReportWriter().Write(SampleReport(), CultureInfo.InvariantCulture);
        var lines = csv.Split('\n', StringSplitOptions.RemoveEmptyEntries);

        Assert.StartsWith("Title,", lines[0]);
        Assert.Equal(2, lines.Length);
        Assert.Contains("Build output", lines[1]);
    }

    [Fact]
    public void Csv_QuotesFieldsContainingTheSeparator()
    {
        var report = SampleReport() with
        {
            Recommendations =
            [
                SampleReport().Recommendations[0] with { Reason = "Large, rebuildable, and safe" }
            ]
        };

        string csv = new CsvReportWriter().Write(report, CultureInfo.InvariantCulture);

        Assert.Contains("\"Large, rebuildable, and safe\"", csv);
    }

    [Fact]
    public void Csv_EscapesEmbeddedQuotes()
    {
        var report = SampleReport() with
        {
            Recommendations = [SampleReport().Recommendations[0] with { Title = "The \"bin\" folder" }]
        };

        string csv = new CsvReportWriter().Write(report, CultureInfo.InvariantCulture);

        Assert.Contains("\"The \"\"bin\"\" folder\"", csv);
    }

    [Fact]
    public void Csv_UsesSemicolonsWhenTheCultureUsesCommaDecimals()
    {
        // Otherwise Excel would split "3,5" across two columns.
        var german = CultureInfo.GetCultureInfo("de-DE");

        string csv = new CsvReportWriter().Write(SampleReport(), german);

        Assert.StartsWith("Title;", csv);
    }

    [Fact]
    public void Csv_StripsNewlinesFromFields()
    {
        var report = SampleReport() with
        {
            Recommendations = [SampleReport().Recommendations[0] with { Reason = "Line one\nLine two" }]
        };

        string csv = new CsvReportWriter().Write(report, CultureInfo.InvariantCulture);
        var lines = csv.Split('\n', StringSplitOptions.RemoveEmptyEntries);

        Assert.Equal(2, lines.Length);
    }

    [Fact]
    public void Csv_EncodingEmitsAUtf8Bom()
    {
        // Excel needs the BOM to detect UTF-8 and render Persian correctly.
        Assert.Equal([0xEF, 0xBB, 0xBF], CsvReportWriter.Encoding.GetPreamble());
    }

    // --- HTML ---

    [Fact]
    public void Html_IsSelfContained()
    {
        string html = new HtmlReportWriter().Write(
            SampleReport(withAi: true), CultureInfo.InvariantCulture, EnglishReportStrings.Instance);

        Assert.StartsWith("<!DOCTYPE html>", html);
        // No external resources: the report must open identically offline.
        Assert.DoesNotContain("<script", html, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("http://", html, StringComparison.OrdinalIgnoreCase);
        Assert.DoesNotContain("<link", html, StringComparison.OrdinalIgnoreCase);
    }

    [Fact]
    public void Html_IsLeftToRightForEnglish()
    {
        string html = new HtmlReportWriter().Write(
            SampleReport(), CultureInfo.GetCultureInfo("en-US"), EnglishReportStrings.Instance);

        Assert.Contains("dir=\"ltr\"", html);
    }

    [Fact]
    public void Html_IsRightToLeftForPersian()
    {
        string html = new HtmlReportWriter().Write(
            SampleReport(), CultureInfo.GetCultureInfo("fa-IR"), EnglishReportStrings.Instance);

        Assert.Contains("dir=\"rtl\"", html);
        Assert.Contains("Vazirmatn", html);
    }

    [Fact]
    public void Html_EncodesUserSuppliedText()
    {
        var report = SampleReport() with
        {
            RootPath = @"C:\<script>alert('x')</script>"
        };

        string html = new HtmlReportWriter().Write(report, CultureInfo.InvariantCulture, EnglishReportStrings.Instance);

        Assert.DoesNotContain("<script>alert", html);
        Assert.Contains("&lt;script&gt;", html);
    }

    [Fact]
    public void Html_ShowsTheAiSectionOnlyWhenPresent()
    {
        var writer = new HtmlReportWriter();

        string withAi = writer.Write(SampleReport(withAi: true), CultureInfo.InvariantCulture, EnglishReportStrings.Instance);
        string withoutAi = writer.Write(SampleReport(), CultureInfo.InvariantCulture, EnglishReportStrings.Instance);

        Assert.Contains("AI analysis", withAi);
        Assert.DoesNotContain("AI analysis", withoutAi);
    }

    [Fact]
    public void Html_ReportsHowManyAiSuggestionsWereDiscarded()
    {
        string html = new HtmlReportWriter().Write(
            SampleReport(withAi: true), CultureInfo.InvariantCulture, EnglishReportStrings.Instance);

        Assert.Contains("2 suggestion(s)", html);
    }

    [Fact]
    public void Html_AlwaysCarriesTheSafetyNote()
    {
        string html = new HtmlReportWriter().Write(
            SampleReport(), CultureInfo.InvariantCulture, EnglishReportStrings.Instance);

        Assert.Contains("has not changed anything", html);
    }

    [Fact]
    public void Html_HandlesAnEmptyReport()
    {
        var empty = new StorageReport
        {
            SessionId = "s",
            RootPath = @"D:\",
            Language = "en"
        };

        string html = new HtmlReportWriter().Write(empty, CultureInfo.InvariantCulture, EnglishReportStrings.Instance);

        Assert.Contains("Nothing worth reclaiming", html);
    }

    [Fact]
    public void Report_TotalsTheReclaimableSpace()
    {
        Assert.Equal(3L * 1024 * 1024 * 1024, SampleReport().TotalReclaimable);
    }
}
