using Storava.Domain.Enums;
using Storava.Rules.Model;

namespace Storava.Rules.Catalog;

/// <summary>Package manager and build caches for .NET, JavaScript and JVM toolchains.</summary>
internal static class DeveloperCacheRules
{
    internal static IEnumerable<StorageRule> All()
    {
        yield return new StorageRule
        {
            Id = "nuget.global-packages",
            Titles = new Dictionary<string, string>
            {
                ["en"] = "NuGet global package cache",
                ["fa"] = "کش سراسری پکیج‌های NuGet"
            },
            Descriptions = new Dictionary<string, string>
            {
                ["en"] = "Every NuGet package your .NET projects restore is stored here and reused across projects. It only grows, and packages are re-downloaded on demand if removed.",
                ["fa"] = "تمام پکیج‌های NuGet که پروژه‌های .NET شما Restore می‌کنند اینجا نگه‌داری و بین پروژه‌ها بازاستفاده می‌شوند. این پوشه فقط بزرگ‌تر می‌شود و در صورت حذف، پکیج‌ها هنگام نیاز دوباره دانلود می‌شوند."
            },
            Patterns = [new RulePattern(@".nuget\packages", RuleMatchTarget.PathSuffix)],
            Category = StorageCategory.PackageCaches,
            Technology = "NuGet",
            RiskLevel = RiskLevel.Low,
            CanDelete = true,
            CanMove = true,
            CanRegenerate = true,
            OfficialMigrationMethod = MigrationMethod.OfficialSetting,
            FallbackMigrationMethod = MigrationMethod.Junction,
            OfficialMigrationHint = "Set the NUGET_PACKAGES environment variable (or globalPackagesFolder in NuGet.config) to the new location.",
            Warnings = new Dictionary<string, string>
            {
                ["en"] = "Restoring projects after clearing this requires an internet connection.",
                ["fa"] = "پس از پاک‌سازی، Restore پروژه‌ها به اتصال اینترنت نیاز دارد."
            },
            Confidence = 0.98
        };

        yield return new StorageRule
        {
            Id = "nuget.http-cache",
            Titles = new Dictionary<string, string>
            {
                ["en"] = "NuGet HTTP cache",
                ["fa"] = "کش HTTP نیوگت"
            },
            Descriptions = new Dictionary<string, string>
            {
                ["en"] = "Cached HTTP responses from NuGet feeds. Purely a network cache and always safe to clear.",
                ["fa"] = "پاسخ‌های HTTP ذخیره‌شده از فیدهای NuGet. این فقط یک کش شبکه است و پاک کردنش همیشه بی‌خطر است."
            },
            Patterns =
            [
                new RulePattern(@"NuGet\v3-cache", RuleMatchTarget.PathSuffix),
                new RulePattern(@"NuGet\http-cache", RuleMatchTarget.PathSuffix)
            ],
            Category = StorageCategory.PackageCaches,
            Technology = "NuGet",
            RiskLevel = RiskLevel.Low,
            CanDelete = true,
            CanMove = false,
            CanRegenerate = true,
            OfficialMigrationMethod = MigrationMethod.OfficialSetting,
            OfficialMigrationHint = "Run 'dotnet nuget locals http-cache --clear' to clear it.",
            Confidence = 0.97
        };

        yield return new StorageRule
        {
            Id = "dotnet.build-output",
            Titles = new Dictionary<string, string>
            {
                ["en"] = "Build output (bin / obj)",
                ["fa"] = "خروجی بیلد (bin / obj)"
            },
            Descriptions = new Dictionary<string, string>
            {
                ["en"] = "Compiled binaries and intermediate build files. Regenerated by the next build, so removing them costs only compile time.",
                ["fa"] = "فایل‌های کامپایل‌شده و میانی بیلد. با بیلد بعدی دوباره ساخته می‌شوند، پس حذف آن‌ها فقط هزینه‌ی زمان کامپایل دارد."
            },
            Patterns =
            [
                new RulePattern("bin"),
                new RulePattern("obj")
            ],
            Category = StorageCategory.BuildArtifacts,
            Technology = ".NET",
            RiskLevel = RiskLevel.Low,
            CanDelete = true,
            CanMove = false,
            CanRegenerate = true,
            OfficialMigrationMethod = MigrationMethod.OfficialSetting,
            OfficialMigrationHint = "Set a shared BaseOutputPath/BaseIntermediateOutputPath in Directory.Build.props, or run 'dotnet clean'.",
            Confidence = 0.72
        };

        yield return new StorageRule
        {
            Id = "visualstudio.solution-cache",
            Titles = new Dictionary<string, string>
            {
                ["en"] = "Visual Studio solution cache (.vs)",
                ["fa"] = "کش سولوشن ویژوال استودیو (.vs)"
            },
            Descriptions = new Dictionary<string, string>
            {
                ["en"] = "Per-solution IDE state: IntelliSense databases, window layout and build telemetry. Visual Studio rebuilds it on next open.",
                ["fa"] = "وضعیت IDE برای هر سولوشن: دیتابیس IntelliSense، چیدمان پنجره‌ها و داده‌های بیلد. ویژوال استودیو در بازکردن بعدی آن را می‌سازد."
            },
            Patterns = [new RulePattern(".vs")],
            Category = StorageCategory.IdeCaches,
            Technology = "Visual Studio",
            RiskLevel = RiskLevel.Low,
            CanDelete = true,
            CanMove = false,
            CanRegenerate = true,
            Warnings = new Dictionary<string, string>
            {
                ["en"] = "Close the solution in Visual Studio first, otherwise files are locked.",
                ["fa"] = "ابتدا سولوشن را در ویژوال استودیو ببندید، وگرنه فایل‌ها قفل هستند."
            },
            Confidence = 0.95
        };

        yield return new StorageRule
        {
            Id = "npm.node-modules",
            Titles = new Dictionary<string, string>
            {
                ["en"] = "node_modules dependencies",
                ["fa"] = "وابستگی‌های node_modules"
            },
            Descriptions = new Dictionary<string, string>
            {
                ["en"] = "Installed JavaScript dependencies for one project. Fully reproducible from package.json and the lock file by reinstalling.",
                ["fa"] = "وابستگی‌های جاوااسکریپت نصب‌شده برای یک پروژه. با نصب مجدد از package.json و فایل lock کاملاً قابل بازتولید است."
            },
            Patterns = [new RulePattern("node_modules")],
            Category = StorageCategory.PackageCaches,
            Technology = "npm",
            RiskLevel = RiskLevel.Low,
            CanDelete = true,
            CanMove = false,
            CanRegenerate = true,
            OfficialMigrationMethod = MigrationMethod.OfficialSetting,
            OfficialMigrationHint = "Reinstall with 'npm ci' (or your package manager's install) when the project is needed again.",
            Warnings = new Dictionary<string, string>
            {
                ["en"] = "Reinstalling needs network access and may resolve slightly different versions without a lock file.",
                ["fa"] = "نصب مجدد به اینترنت نیاز دارد و بدون فایل lock ممکن است نسخه‌های کمی متفاوت نصب شود."
            },
            Confidence = 0.96
        };

        yield return new StorageRule
        {
            Id = "npm.cache",
            Titles = new Dictionary<string, string>
            {
                ["en"] = "npm download cache",
                ["fa"] = "کش دانلود npm"
            },
            Descriptions = new Dictionary<string, string>
            {
                ["en"] = "Tarballs npm downloaded for any project on this machine. Shared and safe to clear.",
                ["fa"] = "بسته‌های دانلودشده‌ی npm برای همه‌ی پروژه‌های این دستگاه. مشترک است و پاک کردنش بی‌خطر است."
            },
            Patterns =
            [
                new RulePattern(@"npm-cache\_cacache", RuleMatchTarget.PathSuffix),
                new RulePattern("npm-cache")
            ],
            Category = StorageCategory.PackageCaches,
            Technology = "npm",
            RiskLevel = RiskLevel.Low,
            CanDelete = true,
            CanMove = true,
            CanRegenerate = true,
            OfficialMigrationMethod = MigrationMethod.OfficialSetting,
            FallbackMigrationMethod = MigrationMethod.Junction,
            OfficialMigrationHint = "Run 'npm config set cache <new path> --global', or clear with 'npm cache clean --force'.",
            Confidence = 0.95
        };

        yield return new StorageRule
        {
            Id = "pnpm.store",
            Titles = new Dictionary<string, string>
            {
                ["en"] = "pnpm content-addressable store",
                ["fa"] = "انبار محتوامحور pnpm"
            },
            Descriptions = new Dictionary<string, string>
            {
                ["en"] = "pnpm's shared package store. Projects hard-link into it, so deleting it breaks existing installs until they are reinstalled.",
                ["fa"] = "انبار مشترک پکیج‌های pnpm. پروژه‌ها با hard link به آن وصل می‌شوند، پس حذف آن نصب‌های موجود را تا نصب مجدد از کار می‌اندازد."
            },
            Patterns =
            [
                new RulePattern(@"pnpm\store", RuleMatchTarget.PathSuffix),
                new RulePattern("pnpm-store")
            ],
            Category = StorageCategory.PackageCaches,
            Technology = "pnpm",
            RiskLevel = RiskLevel.Medium,
            CanDelete = true,
            CanMove = true,
            CanRegenerate = true,
            OfficialMigrationMethod = MigrationMethod.OfficialSetting,
            FallbackMigrationMethod = MigrationMethod.Junction,
            OfficialMigrationHint = "Run 'pnpm config set store-dir <new path>'; the store must stay on the same volume as your projects for hard links to work.",
            Warnings = new Dictionary<string, string>
            {
                ["en"] = "Existing node_modules folders link into this store and will need reinstalling.",
                ["fa"] = "پوشه‌های node_modules موجود به این انبار لینک دارند و نیاز به نصب مجدد خواهند داشت."
            },
            Confidence = 0.93
        };

        yield return new StorageRule
        {
            Id = "yarn.cache",
            Titles = new Dictionary<string, string>
            {
                ["en"] = "Yarn cache",
                ["fa"] = "کش Yarn"
            },
            Descriptions = new Dictionary<string, string>
            {
                ["en"] = "Packages Yarn downloaded for reuse across projects.",
                ["fa"] = "پکیج‌های دانلودشده‌ی Yarn برای بازاستفاده بین پروژه‌ها."
            },
            Patterns =
            [
                new RulePattern(@"Yarn\Cache", RuleMatchTarget.PathSuffix),
                new RulePattern("yarn-cache")
            ],
            Category = StorageCategory.PackageCaches,
            Technology = "Yarn",
            RiskLevel = RiskLevel.Low,
            CanDelete = true,
            CanMove = true,
            CanRegenerate = true,
            OfficialMigrationMethod = MigrationMethod.OfficialSetting,
            FallbackMigrationMethod = MigrationMethod.Junction,
            OfficialMigrationHint = "Run 'yarn config set cacheFolder <new path>', or clear with 'yarn cache clean'.",
            Confidence = 0.93
        };

        yield return new StorageRule
        {
            Id = "gradle.home",
            Titles = new Dictionary<string, string>
            {
                ["en"] = "Gradle caches and distributions",
                ["fa"] = "کش‌ها و توزیع‌های Gradle"
            },
            Descriptions = new Dictionary<string, string>
            {
                ["en"] = "Downloaded dependencies, build caches and Gradle distributions. Typically one of the largest folders on an Android or JVM development machine.",
                ["fa"] = "وابستگی‌های دانلودشده، کش‌های بیلد و توزیع‌های Gradle. معمولاً یکی از حجیم‌ترین پوشه‌ها در سیستم توسعه‌ی اندروید یا JVM است."
            },
            Patterns = [new RulePattern(".gradle")],
            Category = StorageCategory.PackageCaches,
            Technology = "Gradle",
            RiskLevel = RiskLevel.Low,
            CanDelete = true,
            CanMove = true,
            CanRegenerate = true,
            OfficialMigrationMethod = MigrationMethod.OfficialSetting,
            FallbackMigrationMethod = MigrationMethod.Junction,
            OfficialMigrationHint = "Set the GRADLE_USER_HOME environment variable to the new location.",
            Confidence = 0.95
        };

        yield return new StorageRule
        {
            Id = "maven.repository",
            Titles = new Dictionary<string, string>
            {
                ["en"] = "Maven local repository",
                ["fa"] = "مخزن محلی Maven"
            },
            Descriptions = new Dictionary<string, string>
            {
                ["en"] = "Java artifacts Maven resolved for your builds, kept for offline reuse.",
                ["fa"] = "آرتیفکت‌های جاوا که Maven برای بیلدهای شما دریافت کرده و برای استفاده‌ی آفلاین نگه داشته است."
            },
            Patterns = [new RulePattern(@".m2\repository", RuleMatchTarget.PathSuffix)],
            Category = StorageCategory.PackageCaches,
            Technology = "Maven",
            RiskLevel = RiskLevel.Low,
            CanDelete = true,
            CanMove = true,
            CanRegenerate = true,
            OfficialMigrationMethod = MigrationMethod.OfficialSetting,
            FallbackMigrationMethod = MigrationMethod.Junction,
            OfficialMigrationHint = "Set <localRepository> in ~/.m2/settings.xml to the new path.",
            Confidence = 0.95
        };

        yield return new StorageRule
        {
            Id = "jetbrains.caches",
            Titles = new Dictionary<string, string>
            {
                ["en"] = "JetBrains IDE caches",
                ["fa"] = "کش‌های IDE جت‌برینز"
            },
            Descriptions = new Dictionary<string, string>
            {
                ["en"] = "Indexes and local history for Rider, IntelliJ, WebStorm and friends. Rebuilt automatically, at the cost of one slow re-index.",
                ["fa"] = "ایندکس‌ها و تاریخچه‌ی محلی Rider، IntelliJ، WebStorm و مشابه. به‌طور خودکار بازسازی می‌شوند، به بهای یک ایندکس‌گیری کند."
            },
            Patterns =
            [
                new RulePattern(@"JetBrains\Caches", RuleMatchTarget.PathSuffix),
                new RulePattern(@"JetBrains\IdeaIC", RuleMatchTarget.PathContains),
                new RulePattern(@"JetBrains\Rider", RuleMatchTarget.PathContains)
            ],
            Category = StorageCategory.IdeCaches,
            Technology = "JetBrains",
            RiskLevel = RiskLevel.Low,
            CanDelete = true,
            CanMove = true,
            CanRegenerate = true,
            FallbackMigrationMethod = MigrationMethod.Junction,
            Warnings = new Dictionary<string, string>
            {
                ["en"] = "Close the IDE first; re-indexing large solutions can take a while.",
                ["fa"] = "ابتدا IDE را ببندید؛ ایندکس‌گیری مجدد سولوشن‌های بزرگ ممکن است طول بکشد."
            },
            Confidence = 0.9
        };

        yield return new StorageRule
        {
            Id = "git.repository",
            Titles = new Dictionary<string, string>
            {
                ["en"] = "Git repository data",
                ["fa"] = "داده‌های مخزن Git"
            },
            Descriptions = new Dictionary<string, string>
            {
                ["en"] = "The full history of this repository. Deleting it destroys uncommitted and unpushed work permanently.",
                ["fa"] = "کل تاریخچه‌ی این مخزن. حذف آن کارهای کامیت‌نشده و پوش‌نشده را برای همیشه از بین می‌برد."
            },
            Patterns = [new RulePattern(".git")],
            Category = StorageCategory.DeveloperTools,
            Technology = "Git",
            RiskLevel = RiskLevel.High,
            CanDelete = false,
            CanMove = false,
            CanRegenerate = false,
            Warnings = new Dictionary<string, string>
            {
                ["en"] = "Never delete this unless the repository is fully pushed elsewhere. Use 'git gc' to shrink it safely.",
                ["fa"] = "هرگز آن را حذف نکنید مگر اینکه مخزن کاملاً جای دیگری پوش شده باشد. برای کوچک کردن ایمن از «git gc» استفاده کنید."
            },
            Confidence = 0.97
        };
    }
}
